# Generated by Django 4.2.3 on 2023-08-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='sal',
            field=models.IntegerField(),
        ),
    ]
